# Generated by Django 5.0.6 on 2024-10-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='artist',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
