# Generated by Django 5.0.6 on 2024-10-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='yt_video_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
