# Generated by Django 5.0.6 on 2024-10-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_yt_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
